// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class UriContentNativeApi {
  /// Constructor for [UriContentNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UriContentNativeApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  Future<void> getContentFromUri(String arg_url, int arg_requestId) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.UriContentNativeApi.getContentFromUri', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_url, arg_requestId]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class UriContentFlutterApi {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  void onDataReceived(int requestId, Uint8List? data, String? error);

  static void setup(UriContentFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.UriContentFlutterApi.onDataReceived', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.UriContentFlutterApi.onDataReceived was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.UriContentFlutterApi.onDataReceived was null, expected non-null int.');
          final Uint8List? arg_data = (args[1] as Uint8List?);
          final String? arg_error = (args[2] as String?);
          api.onDataReceived(arg_requestId!, arg_data, arg_error);
          return;
        });
      }
    }
  }
}
